### ISSUE TITLE
Error when trying to use eeg-peek (SmartMove protocol)

### ISSUE THREAD

**Issue by FelixQuirm** [translationalneurosurgery/tool-libeep#3]
**Describe the bug**
After installing offspect in a virtual environment, when trying to peek into a .cnt-sourcefile via _eeg-peek_ , I get the error message that the command can't be found.

![eep-peek_error2](https://user-images.githubusercontent.com/42035995/80362373-d0e4c100-8882-11ea-8c8c-a876c58fed9e.png)

**To Reproduce**
Run `eep-peek VvNn_VvNn_1970-01-01_00-00-01.cnt` from command prompt in folder with said .cnt-file

**Expected behavior**
Peek output appears, specifying which events are in the .cnt-file.

**Desktop:**
 - OS: Windows 10

**Additional context**
Offspect-installation was only successful when performed in virtual environment.

**Comment by FelixQuirm** [comment]
I checked again and 1.) The environment is activated and 2.) libeep is installed in it. 

I tried both libeep version 0.2 and 0.3, but with both, the same error as before occures. Any other possible explanation?

**Comment by agricolab** [comment]
How exactly did you install libeep? Can you share the commands you used?

Anaconda installations on Windows can mess up the `PATH`. You can try Win10s Powershell to echo the PATH  [`$Env:Path`](https://superuser.com/questions/1216658/path-environment-variable-windows-10-echo-path-on-command-prompt-shows-only) or [`Get-Command`](https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line) on e.g. `python` or `pip` to inform you about how your path is set up.

**Comment by agricolab** [comment]
On a side note: I would not recommend organizing your data in a subfolder within the tool-offspect repo. It could break when you update with git pull. I recommend to store data outside of the repos internal structure.

**Comment by agricolab** [comment]
What is weird is that you seem to have two environments activated, i.e `(.env)` and `(base)`. Anaconda installations on Windows can mess up the `PATH`. You can try Win10s Powershell to echo the PATH  [`$Env:Path`](https://superuser.com/questions/1216658/path-environment-variable-windows-10-echo-path-on-command-prompt-shows-only) or [`Get-Command`](https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line) on e.g. `python` or `pip` to inform you about how your path is set up.

**Comment by agricolab** [comment]
There might be some mess-up between installation from a wheel, installation in an environment and how the entry-points for command line tools are being set up. Hard to trace.

One option is compiling from source for your local machine.  This usually doesn't make life easier, though. It would require you to install at least cmake, and probably also Visual Studio, and try to compile libeep, following the instructions in the readme: https://github.com/translationalneurosurgery/tool-libeep#windows

It might work on your machine without the need for compilation, if you follow these steps:
1. run `git pull` on the repo. 
2. download https://github.com/translationalneurosurgery/tool-libeep/releases/download/v0.2/libeep-0.2-py3-none-any.whl
3. unzip the `.whl`-file into your local repo root, this should create a libeep folder
4. copy the `__init__.py` file from the `python` folder into the `libeep` folder, overwriting the existing one
5. run `pip install -e .` from the project root

**Comment by agricolab** [comment]
I also updated the most recent version (v0.3.1) to allow an API access to inspect `.cnt`-files with e.g. `libeep.peek("VvNn_VvNn_2000-12-31_23-59-59.cnt")`. 

This might work on your machine without the need for installation, if you follow these steps:
1. run `git pull` on the repo. 
2. download https://github.com/translationalneurosurgery/tool-libeep/releases/download/v0.2/libeep-0.2-py3-none-any.whl
3. unzip the `.whl`-file into your local repo root, this should create a libeep folder
4. copy the `__init__.py` file from the `python` folder into the `libeep` folder, overwriting the existing one
5. run `pip install -e .` from the project root
